<script lang="ts">
  /**
   * 图标组件 - 基于 Lucide 图标库
   * @zhoolg/svelte-admin-framework
   */
  import {
    House,
    Users,
    Settings,
    FileText,
    ChartColumn,
    Shield,
    Bell,
    Search,
    Menu,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    X,
    Plus,
    Minus,
    Check,
    Trash2,
    SquarePen,
    Eye,
    EyeOff,
    Lock,
    LockOpen,
    User,
    UserPlus,
    UserMinus,
    UserCheck,
    LogOut,
    LogIn,
    Calendar,
    Clock,
    Sun,
    Moon,
    Globe,
    Maximize,
    Minimize,
    RefreshCw,
    Download,
    Upload,
    Image,
    File,
    Folder,
    FolderOpen,
    Copy,
    Clipboard,
    Save,
    Printer,
    Mail,
    Phone,
    MapPin,
    Link,
    ExternalLink,
    Info,
    CircleAlert,
    TriangleAlert,
    CircleCheckBig,
    CircleX,
    CircleQuestionMark,
    MessageSquare,
    MessageCircle,
    Send,
    Inbox,
    Tag,
    Bookmark,
    Star,
    Heart,
    ThumbsUp,
    ThumbsDown,
    Share,
    Funnel,
    ArrowUpNarrowWide,
    ArrowDownWideNarrow,
    List,
    Grid3x3,
    Table,
    Columns2,
    Rows2,
    PanelsTopLeft,
    LayoutDashboard,
    PanelLeft,
    Terminal,
    Code,
    Database,
    Server,
    Cloud,
    Zap,
    Power,
    Play,
    Pause,
    CircleStop,
    SkipBack,
    SkipForward,
    Volume1,
    Volume2,
    VolumeX,
    Mic,
    Camera,
    Video,
    Monitor,
    Smartphone,
    Headphones,
    Radio,
    Tv,
    Box,
    Building,
    Building2,
    ShoppingCart,
    ShoppingBag,
    CreditCard,
    Wallet,
    Banknote,
    Coins,
    Receipt,
    Percent,
    ChartLine,
    ChartPie,
    ChartNoAxesColumn,
    Activity,
    Award,
    Medal,
    Sparkles,
    WandSparkles,
    Palette,
    Paintbrush,
    Pencil,
    Pen,
    Eraser,
    Highlighter,
    ListChecks,
    Maximize2,
    Minimize2,
    Move,
    Undo,
    Redo,
    History,
    Timer,
    CalendarPlus,
    CalendarMinus,
    CalendarX,
    Bot,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ChevronsUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    CircleArrowUp,
    CircleArrowDown,
    CircleArrowLeft,
    CircleArrowRight,
    Reply,
    Briefcase,
    Map,
    Navigation,
    Compass,
    Car,
    Plane,
    Rocket,
    Gift,
    Trophy,
    Crown,
    Gem,
    Glasses,
    Accessibility,
    HeartPulse,
    Stethoscope,
    Syringe,
    Pill,
    Thermometer,
    Brain,
    Bone,
    Skull,
    Baby,
    PersonStanding,
    Dna,
    Microscope,
    FlaskConical,
    TestTube,
    Atom,
    Scan,
    QrCode,
    Barcode,
    Hand,
    Bike,
    Waves,
    Satellite,
    FileSpreadsheet,
    Circle,
    Trees,
    Leaf,
    Flame,
    Snowflake,
  } from 'lucide-svelte';

  interface Props {
    name: string;
    size?: number;
    class?: string;
    strokeWidth?: number;
  }

  let { name, size = 18, class: className = '', strokeWidth = 2 }: Props = $props();

  // 图标映射表
  const iconMap: Record<string, typeof House> = {
    // 导航和菜单
    home: House,
    bars: Menu,
    menu: Menu,
    'angle-down': ChevronDown,
    'angle-up': ChevronUp,
    'angle-left': ChevronLeft,
    'angle-right': ChevronRight,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,

    // 用户相关
    user: User,
    users: Users,
    'user-plus': UserPlus,
    'user-minus': UserMinus,
    'user-edit': UserCheck,
    'sign-out': LogOut,
    'sign-in': LogIn,
    lock: Lock,
    unlock: LockOpen,
    key: Lock,

    // 操作
    search: Search,
    plus: Plus,
    minus: Minus,
    times: X,
    check: Check,
    trash: Trash2,
    pencil: SquarePen,
    edit: SquarePen,
    eye: Eye,
    'eye-slash': EyeOff,
    refresh: RefreshCw,
    sync: RefreshCw,
    download: Download,
    upload: Upload,
    copy: Copy,
    clipboard: Clipboard,
    save: Save,
    print: Printer,
    filter: Funnel,
    'sort-alt': ArrowUpNarrowWide,
    'sort-amount-up': ArrowUpNarrowWide,
    'sort-amount-down': ArrowDownWideNarrow,

    // 通知和消息
    bell: Bell,
    envelope: Mail,
    inbox: Inbox,
    send: Send,
    comment: MessageSquare,
    comments: MessageCircle,

    // 设置和配置
    cog: Settings,
    settings: Settings,

    // 文件和文档
    file: File,
    'file-edit': FileText,
    folder: Folder,
    'folder-open': FolderOpen,
    image: Image,
    images: Image,

    // 日期和时间
    calendar: Calendar,
    'calendar-plus': CalendarPlus,
    'calendar-minus': CalendarMinus,
    'calendar-times': CalendarX,
    clock: Clock,
    history: History,

    // 主题
    sun: Sun,
    moon: Moon,

    // 全局
    globe: Globe,
    language: Globe,

    // 窗口
    'window-maximize': Maximize,
    'window-minimize': Minimize,
    'external-link': ExternalLink,
    link: Link,

    // 状态和提示
    info: Info,
    'info-circle': Info,
    'exclamation-triangle': TriangleAlert,
    'exclamation-circle': CircleAlert,
    'check-circle': CircleCheckBig,
    'times-circle': CircleX,
    'question-circle': CircleQuestionMark,
    ban: CircleX,

    // 图表和数据
    'chart-bar': ChartColumn,
    'chart-line': ChartLine,
    'chart-pie': ChartPie,
    database: Database,
    server: Server,
    table: Table,
    list: List,
    'th-large': Grid3x3,

    // 购物和商业
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    'credit-card': CreditCard,
    wallet: Wallet,
    'money-bill': Banknote,
    dollar: Banknote,
    percentage: Percent,
    receipt: Receipt,

    // 标签和分类
    tag: Tag,
    tags: Tag,
    bookmark: Bookmark,
    star: Star,
    heart: Heart,

    // 布局
    th: LayoutDashboard,
    columns: Columns2,
    rows: Rows2,
    sidebar: PanelLeft,
    layout: PanelsTopLeft,

    // 安全
    shield: Shield,
    verified: Shield,

    // 其他
    bolt: Zap,
    'power-off': Power,
    spinner: RefreshCw,
    box: Box,
    building: Building,
    briefcase: Briefcase,
    phone: Phone,
    mobile: Smartphone,
    'map-marker': MapPin,
    map: Map,
    compass: Compass,
    directions: Navigation,
    car: Car,
    plane: Plane,
    rocket: Rocket,
    gift: Gift,
    trophy: Trophy,
    crown: Crown,
    palette: Palette,
    'paint-brush': Paintbrush,
    code: Code,
    terminal: Terminal,
    cloud: Cloud,
    video: Video,
    camera: Camera,
    microphone: Mic,
    'volume-up': Volume2,
    'volume-down': Volume1,
    'volume-off': VolumeX,
    play: Play,
    pause: Pause,
    stop: CircleStop,
    forward: SkipForward,
    backward: SkipBack,
    expand: Maximize2,
    compress: Minimize2,
    'arrows-alt': Move,
    undo: Undo,
    redo: Redo,
    reply: Reply,
    share: Share,
    robot: Bot,
    sparkles: Sparkles,
    'wand-magic-sparkles': WandSparkles,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    medal: Medal,
    stopwatch: Timer,
    gem: Gem,
    glasses: Glasses,
    hospital: Building2,
    stethoscope: Stethoscope,
    syringe: Syringe,
    pills: Pill,
    thermometer: Thermometer,
    heartbeat: HeartPulse,
    brain: Brain,
    bone: Bone,
    dna: Dna,
    microscope: Microscope,
    flask: FlaskConical,
    atom: Atom,
    baby: Baby,
    walking: PersonStanding,
    biking: Bike,
    'swimming-pool': Waves,
    dumbbell: Activity,
    'broadcast-tower': Radio,
    'satellite-dish': Satellite,
    qrcode: QrCode,
    barcode: Barcode,
    hands: Hand,
    handshake: Hand,
    'file-excel': FileSpreadsheet,
    skull: Skull,
    wheelchair: Accessibility,
    scan: Scan,
    fire: Flame,
    snowflake: Snowflake,
    leaf: Leaf,
    tree: Trees,
    coins: Coins,
    tv: Tv,
    headphones: Headphones,
    monitor: Monitor,
    pencil: Pencil,
    pen: Pen,
    eraser: Eraser,
    highlighter: Highlighter,
    tasks: ListChecks,
    'angle-double-up': ChevronsUp,
    'angle-double-down': ChevronsDown,
    'angle-double-left': ChevronsLeft,
    'angle-double-right': ChevronsRight,
    'arrow-circle-up': CircleArrowUp,
    'arrow-circle-down': CircleArrowDown,
    'arrow-circle-left': CircleArrowLeft,
    'arrow-circle-right': CircleArrowRight,
    award: Award,
  };

  // 获取图标组件
  const IconComponent = $derived(iconMap[name] || CircleQuestionMark);
</script>

<svelte:component this={IconComponent} {size} class={className} {strokeWidth} />
