<script lang="ts">
  /**
   * 图标组件 - 基于 Lucide 图标库
   * 用于统一管理和渲染图标
   */
  import {
    House,
    Users,
    Settings,
    FileText,
    ChartColumn,
    Shield,
    Bell,
    Search,
    Menu,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    X,
    Plus,
    Minus,
    Check,
    Trash2,
    SquarePen,
    Eye,
    EyeOff,
    Lock,
    LockOpen,
    User,
    UserPlus,
    UserMinus,
    UserCheck,
    LogOut,
    LogIn,
    Calendar,
    Clock,
    Sun,
    Moon,
    Globe,
    Maximize,
    Minimize,
    RefreshCw,
    Download,
    Upload,
    Image,
    File,
    Folder,
    FolderOpen,
    Copy,
    Clipboard,
    Save,
    Printer,
    Mail,
    Phone,
    MapPin,
    Link,
    ExternalLink,
    Info,
    CircleAlert,
    TriangleAlert,
    CircleCheckBig,
    CircleX,
    CircleQuestionMark,
    MessageSquare,
    MessageCircle,
    Send,
    Inbox,
    Archive,
    Tag,
    Bookmark,
    Star,
    Heart,
    ThumbsUp,
    ThumbsDown,
    Share,
    Funnel,
    ArrowUpNarrowWide,
    ArrowDownWideNarrow,
    List,
    Grid3x3,
    Table,
    Columns2,
    Rows2,
    PanelsTopLeft,
    LayoutDashboard,
    PanelLeft,
    PanelRight,
    Terminal,
    Code,
    Database,
    Server,
    Cloud,
    Wifi,
    WifiOff,
    Bluetooth,
    Battery,
    Zap,
    Power,
    Play,
    Pause,
    CircleStop,
    SkipBack,
    SkipForward,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Mic,
    MicOff,
    Camera,
    Video,
    VideoOff,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Headphones,
    Speaker,
    Radio,
    Tv,
    Cast,
    Airplay,
    Cpu,
    HardDrive,
    Usb,
    Plug,
    Router,
    Signal,
    Satellite,
    Navigation,
    Compass,
    Map,
    Mountain,
    Trees,
    Flower2,
    Leaf,
    Sun as SunIcon,
    Moon as MoonIcon,
    Cloud as CloudIcon,
    CloudRain,
    CloudSnow,
    CloudLightning,
    Wind,
    Droplet,
    Thermometer,
    Umbrella,
    Snowflake,
    Flame,
    Waves,
    Anchor,
    Ship,
    Plane,
    Car,
    Bus,
    Bike,
    Footprints,
    Rocket,
    Briefcase,
    Building,
    Building2,
    Factory,
    Store,
    ShoppingCart,
    ShoppingBag,
    Package,
    Gift,
    CreditCard,
    Wallet,
    Banknote,
    Coins,
    PiggyBank,
    Receipt,
    Calculator,
    Percent,
    TrendingUp,
    TrendingDown,
    Activity,
    ChartPie,
    ChartLine,
    ChartNoAxesColumnIncreasing,
    ChartNoAxesColumn,
    Gauge,
    Target,
    Award,
    Trophy,
    Medal,
    Crown,
    Gem,
    Diamond,
    Sparkles,
    WandSparkles,
    Palette,
    Paintbrush,
    Pencil,
    Pen,
    Eraser,
    Highlighter,
    Type,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    ListOrdered,
    ListChecks,
    Quote,
    Heading1,
    Heading2,
    Heading3,
    Pilcrow,
    Scissors,
    Crop,
    Move,
    Maximize2,
    Minimize2,
    ZoomIn,
    ZoomOut,
    RotateCw,
    RotateCcw,
    FlipHorizontal,
    FlipVertical,
    Layers,
    Square,
    Circle,
    Triangle,
    Hexagon,
    Octagon,
    Pentagon,
    RectangleHorizontal,
    RectangleVertical,
    Shapes,
    Box,
    Boxes,
    Orbit,
    Atom,
    Dna,
    Microscope,
    FlaskConical,
    TestTube,
    Pill,
    Syringe,
    Stethoscope,
    Thermometer as ThermometerIcon,
    HeartPulse,
    Brain,
    Bone,
    Skull,
    Baby,
    PersonStanding,
    Accessibility,
    Glasses,
    Hand,
    Scan,
    ScanLine,
    QrCode,
    Barcode,
    Hash,
    AtSign,
    Asterisk,
    Slash,
    Equal,
    Infinity,
    Pi,
    Sigma,
    Binary,
    FileCode,
    FileType,
    FileCog,
    FileSearch,
    FileCheck,
    FileX,
    FilePlus,
    FileMinus,
    FileInput,
    FileOutput,
    FileSymlink,
    FileArchive,
    FileImage,
    FileSpreadsheet,
    FileText as FileTextIcon,
    FilePen,
    FileHeart,
    FileLock,
    FileKey,
    Files,
    FolderPlus,
    FolderMinus,
    FolderCheck,
    FolderX,
    FolderSearch,
    FolderCog,
    FolderSync,
    FolderInput,
    FolderOutput,
    FolderArchive,
    FolderLock,
    FolderKey,
    FolderHeart,
    Folders,
    BellOff,
    BellRing,
    BellPlus,
    BellMinus,
    BellDot,
    MailOpen,
    MailPlus,
    MailMinus,
    MailCheck,
    MailX,
    MailSearch,
    MailWarning,
    Mails,
    Inbox as InboxIcon,
    Send as SendIcon,
    Forward,
    Reply,
    ReplyAll,
    CornerUpLeft,
    CornerUpRight,
    CornerDownLeft,
    CornerDownRight,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUpLeft,
    ArrowUpRight,
    ArrowDownLeft,
    ArrowDownRight,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    ChevronsUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ArrowBigUp,
    ArrowBigDown,
    ArrowBigLeft,
    ArrowBigRight,
    CircleArrowUp,
    CircleArrowDown,
    CircleArrowLeft,
    CircleArrowRight,
    Undo,
    Redo,
    Undo2,
    Redo2,
    History,
    TimerReset,
    Timer,
    TimerOff,
    Hourglass,
    AlarmClock,
    AlarmClockOff,
    CalendarDays,
    CalendarRange,
    CalendarCheck,
    CalendarX,
    CalendarPlus,
    CalendarMinus,
    CalendarSearch,
    CalendarClock,
    CalendarHeart,
    Bot,
    BotMessageSquare,
    Sparkle,
    type Icon as IconType,
  } from 'lucide-svelte';

  interface Props {
    name: string;
    size?: number;
    class?: string;
    strokeWidth?: number;
  }

  let { name, size = 18, class: className = '', strokeWidth = 2 }: Props = $props();

  // 图标映射表 - PrimeIcons 名称到 Lucide 组件
  const iconMap: Record<string, typeof House> = {
    // 导航和菜单
    home: House,
    bars: Menu,
    menu: Menu,
    'angle-down': ChevronDown,
    'angle-up': ChevronUp,
    'angle-left': ChevronLeft,
    'angle-right': ChevronRight,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,

    // 用户相关
    user: User,
    users: Users,
    'user-plus': UserPlus,
    'user-minus': UserMinus,
    'user-edit': UserCheck,
    'sign-out': LogOut,
    'sign-in': LogIn,
    lock: Lock,
    unlock: LockOpen,
    key: Lock,

    // 操作
    search: Search,
    plus: Plus,
    minus: Minus,
    times: X,
    check: Check,
    trash: Trash2,
    pencil: SquarePen,
    edit: SquarePen,
    eye: Eye,
    'eye-slash': EyeOff,
    refresh: RefreshCw,
    sync: RefreshCw,
    download: Download,
    upload: Upload,
    copy: Copy,
    clipboard: Clipboard,
    save: Save,
    print: Printer,
    filter: Funnel,
    'filter-slash': Funnel,
    'sort-alt': ArrowUpNarrowWide,
    'sort-amount-up': ArrowUpNarrowWide,
    'sort-amount-down': ArrowDownWideNarrow,

    // 通知和消息
    bell: Bell,
    'bell-slash': BellOff,
    envelope: Mail,
    inbox: Inbox,
    send: Send,
    comment: MessageSquare,
    comments: MessageCircle,

    // 设置和配置
    cog: Settings,
    'sliders-h': Settings,
    'sliders-v': Settings,

    // 文件和文档
    file: File,
    'file-edit': FileText,
    'file-pdf': FileText,
    'file-excel': FileSpreadsheet,
    'file-word': FileText,
    folder: Folder,
    'folder-open': FolderOpen,
    image: Image,
    images: Image,

    // 日期和时间
    calendar: Calendar,
    'calendar-plus': CalendarPlus,
    'calendar-minus': CalendarMinus,
    'calendar-times': CalendarX,
    clock: Clock,
    history: History,

    // 主题
    sun: Sun,
    moon: Moon,

    // 全局
    globe: Globe,
    language: Globe,

    // 窗口
    'window-maximize': Maximize,
    'window-minimize': Minimize,
    'external-link': ExternalLink,
    link: Link,

    // 状态和提示
    info: Info,
    'info-circle': Info,
    'exclamation-triangle': TriangleAlert,
    'exclamation-circle': CircleAlert,
    'check-circle': CircleCheckBig,
    'times-circle': CircleX,
    'question-circle': CircleQuestionMark,
    ban: CircleX,

    // 图表和数据
    'chart-bar': ChartColumn,
    'chart-line': ChartLine,
    'chart-pie': ChartPie,
    database: Database,
    server: Server,
    table: Table,
    list: List,
    'th-large': Grid3x3,

    // 购物和商业
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    'credit-card': CreditCard,
    wallet: Wallet,
    'money-bill': Banknote,
    dollar: Banknote,
    percentage: Percent,
    receipt: Receipt,

    // 标签和分类
    tag: Tag,
    tags: Tag,
    bookmark: Bookmark,
    star: Star,
    'star-fill': Star,
    heart: Heart,
    'heart-fill': Heart,

    // 布局
    th: LayoutDashboard,
    columns: Columns2,
    rows: Rows2,
    sidebar: PanelLeft,
    layout: PanelsTopLeft,

    // 安全
    shield: Shield,
    verified: Shield,

    // 其他
    bolt: Zap,
    'power-off': Power,
    spinner: RefreshCw,
    'circle-notch': RefreshCw,
    'ellipsis-h': Menu,
    'ellipsis-v': Menu,
    'grip-vertical': Menu,
    'grip-horizontal': Menu,
    box: Box,
    building: Building,
    briefcase: Briefcase,
    phone: Phone,
    mobile: Smartphone,
    'map-marker': MapPin,
    map: Map,
    compass: Compass,
    directions: Navigation,
    car: Car,
    truck: Car,
    plane: Plane,
    rocket: Rocket,
    gift: Gift,
    trophy: Trophy,
    crown: Crown,
    palette: Palette,
    'paint-brush': Paintbrush,
    code: Code,
    terminal: Terminal,
    cloud: Cloud,
    'cloud-upload': Upload,
    'cloud-download': Download,
    wifi: Wifi,
    video: Video,
    camera: Camera,
    microphone: Mic,
    'volume-up': Volume2,
    'volume-down': Volume1,
    'volume-off': VolumeX,
    play: Play,
    pause: Pause,
    stop: CircleStop,
    forward: SkipForward,
    backward: SkipBack,
    expand: Maximize2,
    compress: Minimize2,
    'arrows-alt': Move,
    undo: Undo,
    redo: Redo,
    reply: Reply,
    share: Share,
    android: Smartphone,
    apple: Smartphone,
    windows: Monitor,
    linux: Terminal,
    github: Code,
    gitlab: Code,
    bitbucket: Code,
    slack: MessageSquare,
    discord: MessageSquare,
    twitter: MessageCircle,
    facebook: MessageCircle,
    instagram: Camera,
    youtube: Video,
    linkedin: Briefcase,
    google: Globe,
    amazon: ShoppingCart,
    paypal: CreditCard,
    stripe: CreditCard,
    bitcoin: Coins,
    ethereum: Coins,
    qrcode: QrCode,
    barcode: Barcode,
    'id-card': CreditCard,
    'address-book': Users,
    'address-card': User,
    sitemap: LayoutDashboard,
    'project-diagram': LayoutDashboard,
    tasks: ListChecks,
    'clipboard-list': Clipboard,
    'clipboard-check': Clipboard,
    poll: ChartNoAxesColumn,
    'vote-yea': ThumbsUp,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    lightbulb: Sparkles,
    'graduation-cap': Award,
    book: FileText,
    'book-open': FileText,
    newspaper: FileText,
    rss: Radio,
    podcast: Headphones,
    headphones: Headphones,
    music: Headphones,
    film: Video,
    tv: Tv,
    gamepad: Smartphone,
    'puzzle-piece': Shapes,
    magic: WandSparkles,
    fire: Flame,
    snowflake: Snowflake,
    leaf: Leaf,
    tree: Trees,
    seedling: Leaf,
    bug: CircleAlert,
    virus: CircleAlert,
    biohazard: TriangleAlert,
    radiation: TriangleAlert,
    recycle: RefreshCw,
    'trash-alt': Trash2,
    eraser: Eraser,
    highlighter: Highlighter,
    marker: Pen,
    pen: Pen,
    'pencil-alt': Pencil,
    quill: Pen,
    feather: Pen,
    signature: Pen,
    stamp: FileCheck,
    certificate: Award,
    ribbon: Award,
    medal: Medal,
    gem: Gem,
    ring: Circle,
    glasses: Glasses,
    sunglasses: Glasses,
    blind: EyeOff,
    deaf: CircleQuestionMark,
    wheelchair: Accessibility,
    crutch: Accessibility,
    'first-aid': HeartPulse,
    hospital: Building2,
    'clinic-medical': Building2,
    stethoscope: Stethoscope,
    syringe: Syringe,
    pills: Pill,
    capsules: Pill,
    'prescription-bottle': Pill,
    thermometer: Thermometer,
    heartbeat: HeartPulse,
    'heart-broken': Heart,
    brain: Brain,
    tooth: Circle,
    bone: Bone,
    'x-ray': Scan,
    dna: Dna,
    microscope: Microscope,
    vial: TestTube,
    vials: TestTube,
    flask: FlaskConical,
    atom: Atom,
    robot: Bot,
    'user-robot': Bot,
    'android-alt': Bot,
    sparkles: Sparkles,
    'wand-magic-sparkles': WandSparkles,
    'hat-wizard': WandSparkles,
    scroll: FileText,
    'book-skull': Skull,
    ghost: Skull,
    'skull-crossbones': Skull,
    cat: Baby,
    dog: Baby,
    horse: Baby,
    dragon: Baby,
    hippo: Baby,
    otter: Baby,
    fish: Baby,
    frog: Baby,
    crow: Baby,
    dove: Baby,
    'kiwi-bird': Baby,
    spider: Baby,
    mosquito: Baby,
    locust: Baby,
    shrimp: Baby,
    worm: Baby,
    bacteria: Baby,
    paw: Baby,
    'feather-alt': Pen,
    egg: Circle,
    bacon: Circle,
    hamburger: Circle,
    hotdog: Circle,
    'pizza-slice': Circle,
    cheese: Circle,
    'bread-slice': Circle,
    cookie: Circle,
    'ice-cream': Circle,
    'candy-cane': Circle,
    lemon: Circle,
    'apple-alt': Circle,
    carrot: Circle,
    'pepper-hot': Circle,
    'drumstick-bite': Circle,
    'wine-glass': Circle,
    'wine-bottle': Circle,
    beer: Circle,
    cocktail: Circle,
    'glass-martini': Circle,
    coffee: Circle,
    'mug-hot': Circle,
    utensils: Circle,
    spoon: Circle,
    blender: Circle,
    'mortar-pestle': Circle,
    stroopwafel: Circle,
    'birthday-cake': Gift,
    'cookie-bite': Circle,
    question: CircleQuestionMark,
    'minus-circle': Minus,
    'plus-circle': Plus,
    'stop-circle': CircleX,
    'play-circle': Play,
    'pause-circle': Pause,
    'arrow-circle-up': CircleArrowUp,
    'arrow-circle-down': CircleArrowDown,
    'arrow-circle-left': CircleArrowLeft,
    'arrow-circle-right': CircleArrowRight,
    'sort-up': ArrowUp,
    'sort-down': ArrowDown,
    'caret-up': ChevronUp,
    'caret-down': ChevronDown,
    'caret-left': ChevronLeft,
    'caret-right': ChevronRight,
    'angle-double-up': ChevronsUp,
    'angle-double-down': ChevronsDown,
    'angle-double-left': ChevronsLeft,
    'angle-double-right': ChevronsRight,
    'long-arrow-alt-up': ArrowUp,
    'long-arrow-alt-down': ArrowDown,
    'long-arrow-alt-left': ArrowLeft,
    'long-arrow-alt-right': ArrowRight,
    'exchange-alt': RefreshCw,
    random: RefreshCw,
    retweet: RefreshCw,
    'level-up-alt': ArrowUp,
    'level-down-alt': ArrowDown,
    'sign-in-alt': LogIn,
    'sign-out-alt': LogOut,
    'door-open': LogOut,
    'door-closed': LogIn,
    dungeon: Building,
    'fort-awesome': Building,
    'chess-rook': Building,
    monument: Building,
    landmark: Building,
    university: Building,
    school: Building,
    church: Building,
    mosque: Building,
    synagogue: Building,
    'torii-gate': Building,
    vihara: Building,
    kaaba: Building,
    'place-of-worship': Building,
    'praying-hands': Hand,
    hands: Hand,
    'hand-paper': Hand,
    'hand-rock': Hand,
    'hand-scissors': Hand,
    'hand-lizard': Hand,
    'hand-spock': Hand,
    'hand-peace': Hand,
    'hand-point-up': Hand,
    'hand-point-down': Hand,
    'hand-point-left': Hand,
    'hand-point-right': Hand,
    'hand-pointer': Hand,
    'hand-middle-finger': Hand,
    'fist-raised': Hand,
    'hand-holding': Hand,
    'hand-holding-heart': Hand,
    'hand-holding-usd': Hand,
    'hand-holding-water': Hand,
    'hand-holding-medical': Hand,
    'hands-helping': Hand,
    handshake: Hand,
    'people-arrows': Users,
    'people-carry': Users,
    'user-friends': Users,
    'user-group': Users,
    'users-cog': Users,
    'user-cog': User,
    'user-shield': User,
    'user-lock': User,
    'user-clock': User,
    'user-check': UserCheck,
    'user-times': UserMinus,
    'user-slash': UserMinus,
    'user-injured': User,
    'user-nurse': User,
    'user-md': User,
    'user-graduate': User,
    'user-astronaut': User,
    'user-ninja': User,
    'user-secret': User,
    'user-tie': User,
    'user-tag': User,
    'user-alt': User,
    'user-alt-slash': UserMinus,
    'user-circle': User,
    'id-badge': User,
    portrait: User,
    male: User,
    female: User,
    genderless: User,
    transgender: User,
    'transgender-alt': User,
    venus: User,
    mars: User,
    'venus-mars': Users,
    'venus-double': Users,
    'mars-double': Users,
    mercury: User,
    neuter: User,
    restroom: Users,
    baby: Baby,
    'baby-carriage': Baby,
    child: Baby,
    'person-booth': User,
    walking: PersonStanding,
    running: PersonStanding,
    hiking: PersonStanding,
    biking: Bike,
    'swimming-pool': Waves,
    skiing: PersonStanding,
    'skiing-nordic': PersonStanding,
    skating: PersonStanding,
    snowboarding: PersonStanding,
    'golf-ball': Circle,
    'football-ball': Circle,
    futbol: Circle,
    'basketball-ball': Circle,
    'baseball-ball': Circle,
    'volleyball-ball': Circle,
    'hockey-puck': Circle,
    'table-tennis': Circle,
    'bowling-ball': Circle,
    quidditch: Circle,
    dumbbell: Activity,
    'weight-hanging': Activity,
    'medal-alt': Medal,
    stopwatch: Timer,
    'stopwatch-20': Timer,
    flag: Bookmark,
    'flag-checkered': Bookmark,
    'flag-usa': Bookmark,
    'font-awesome-flag': Bookmark,
    pennant: Bookmark,
    bullhorn: Volume2,
    megaphone: Volume2,
    'broadcast-tower': Radio,
    'satellite-dish': Satellite,
    'space-shuttle': Rocket,
    'user-astronaut-alt': Rocket,
    meteor: Sparkles,
    'moon-alt': Moon,
    'sun-alt': Sun,
    stars: Star,
    'star-half': Star,
    'star-half-alt': Star,
    'star-of-life': Star,
    'star-of-david': Star,
    'yin-yang': Circle,
    peace: Circle,
    om: Circle,
    khanda: Circle,
    dharmachakra: Circle,
    cross: Plus,
    ankh: Plus,
    bible: FileText,
    quran: FileText,
    torah: FileText,
    menorah: Sparkles,
    hanukiah: Sparkles,
    hamsa: Hand,
    jedi: Star,
    'journal-whills': FileText,
    'galactic-republic': Circle,
    'galactic-senate': Circle,
    'old-republic': Circle,
    rebel: Circle,
    empire: Circle,
    sith: Circle,
    mandalorian: Circle,
    'baby-yoda': Baby,
  };

  // 获取图标组件
  const IconComponent = $derived(iconMap[name] || CircleQuestionMark);
</script>

<svelte:component this={IconComponent} {size} class={className} {strokeWidth} />
